### ISSUE TITLE
[Request] GUI and Executable

### ISSUE THREAD

**Issue by MorganTheGull** [cshock159/HUDAlert#1]
Recommendation to add a GUI to allow for:

- Start & Stop of the program
- Settings Page

Variable Settings Options
- Confidence Threshold
- Detect Time
- Sounds On/Off
- Custom Sound

Also requesting this to be made into an executable so people don't need to do the python setup and can easily just run it.

**Comment by cshock159** [comment]
Progress update on the below. These are all merged. 

Start & Stop of the program ✔️ 
Settings Page ✔️ 
Variable Settings Options ✔️ 

Confidence Threshold ✔️ 
Detect Time ✔️ 
Sounds On/Off ✔️ 
EXE ❌ 
Custom Sound ❌

**Comment by cshock159** [comment]
Exe is finished. It can be found in the releases section https://github.com/cshock159/HUDs-Up/releases/tag/v1
I'm holding off on custom sound for now.
